In [1]:
import numpy as np, pandas as pd

In [2]:
# Crie uma matriz 1D com números de 0 a 9
np_array = np.arange(0, 10)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Crie uma matriz booleana numpy 3×3 com ‘True’
np_matrix = np.array([True] * 9).reshape(3, 3)
np_matrix

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
# Extraia todos os números ímpares de ‘arr’
keep_odds = lambda l: np.array([x for x in l if x % 2 == 1])
keep_odds(np_array)

np.extract(np.mod(np_array, 2) == 1, np_array)

array([1, 3, 5, 7, 9])

In [5]:
# Substitua todos os números ímpares arr por -1
replace_odds = lambda l: np.array([x if x % 2 == 0 else -1 for x in l])
replace_odds(np_array)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [6]:
# Empilhe matrizes verticalmente:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate((a, b)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
# Empilhe as matrizes horizontalmente:
# a = np.arange(10).reshape(2,-1)
# b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate((a, b), axis=1))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [8]:
# Crie o seguinte padrão sem codificação: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]).
# Usando apenas funções numpy e a matriz de entrada abaixo ‘a’.
a = np.array([1,2,3])
np.concatenate((a.reshape(3, 1).repeat(3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
# Calcule a pontuação softmax de ‘sepal length’:
iris = np.genfromtxt('../input/iris.data', delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

sepallength = iris[:, 0]
np.exp(sepallength) / np.sum(np.exp(sepallength), axis=0)

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814

In [41]:
# Filtre as linhas de iris_2d que possuem petallength (coluna 3) > 1.5 e sepallength (coluna 1) < 5.0
iris[(iris[:,2] > 1.5) & (iris[:,0] < 5.0)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [42]:
# Selecione as linhas de iris_2d que não têm nenhum valor ‘nan’
iris[~np.isnan(iris).any(axis=1)]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [46]:
# Calcule as contagens de valores únicos na linha.
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

print('\nQuantidade única em cada linha: ', [len(np.unique(x)) for x in arr])

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]

Quantidade única em cada linha:  [7, 7, 5, 7, 7, 8]


In [58]:
# Calcule as codificações únicas (variáveis binárias dummy para cada valor único na matriz)
np.random.seed(101)
arr = np.random.randint(1,4, size=6)

dummies = np.zeros((len(arr), np.max(arr)))
for i in range(len(arr)):
    dummies[i][arr[i] - 1] = 1

print(arr)
print(dummies)

[2 3 2 2 2 1]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
